### ISSUE TITLE
Is pkg-config a runtime requirement of PyCBC?

### ISSUE THREAD

**Issue by duncanmmacleod** [conda-forge/pycbc-feedstock#3]
When I run `pycbc` from its conda installation, I am given what appears to be a warning (rather than failure) regarding pkg-config. Should it be a runtime requirement?
```
[submit:~] singularity run  /cvmfs/ligo-containers.opensciencegrid.org/lscsoft/conda/nightly ligo-py27 pycbc_make_psd_estimation_workflow --help
PyCBC.libutils: pkg-config call failed, setting NO_PKGCONFIG=1
...
(--help information)
...
```
I'll add that it's a bit of an odd runtime dependency, if so.

_Originally posted by @tpdownes in https://github.com/conda-forge/pycbc-feedstock/pull/2#issuecomment-460288680_

**Comment by duncanmmacleod** [comment]
@ahnitz, can you comment on this?

**Comment by ahnitz** [comment]
@duncanmmacleod It is optional, but not a requirement. We could think of silencing this is most cases.

**Comment by duncanmmacleod** [comment]
@ahnitz, can you describe how it is used?

**Comment by ahnitz** [comment]
It is used to help find other optional components. If it's not available, one must resort to standard location / environment variables.

**Comment by duncanmmacleod** [comment]
Are the optional components related to optimisation? Since conda has much wider support for non-python than, say, pip, we might consider opting users into optimisations by default, since we can.

**Comment by ahnitz** [comment]
@duncanmmacleod Yes, indeed. Perhaps it does make sense to add it as a dependency for conda then?

**Comment by duncanmmacleod** [comment]
If its just `mkl` then we should _not_ add that at this time, mainly because we aren't distributing `lal` built with MKL just yet and that might present conflicts. Once conda-forge/lal-feedstock#16 is resolved one way or another we can think about it properly.

I'll add `pkg-config` as a dependency anyway so that users don't get handed the above warning.

**Comment by ahnitz** [comment]
@duncanmmacleod Ok, one thing to keep in mind is that for pycbc MKL is just another runtime library we call into. We don't depend on whether lalsuite uses it or not. In practice we don't compile lalsuite with icc or link it to MKL.
